/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hashtable;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
  @Test
  void hashTable() {

    HashTable<String, java.lang.constant.Constable> testTable = new HashTable<>();
    testTable.add("Test", 8);
    assertEquals(6, testTable.hash("Test"));
    assertEquals(" [ {Test:8} ] ", testTable.printOneBucket("Test"));
    assertEquals("hashTable =[null, null, null, null, null, null,  [ {Test:8} ] , null, null, null]", testTable.toString());
    assertEquals(8, testTable.get("Test"));
    assertNull(testTable.get("null"));
    testTable.add("ddd" , "ddd Value");
    testTable.add("Cat" , "Cat Value");
    assertEquals(" [ {Cat:Cat Value} {ddd:ddd Value} ] ", testTable.printOneBucket("Cat"));
    assertEquals("hashTable =[ [ {Cat:Cat Value} {ddd:ddd Value} ] , null, null, null, null, null,  [ {Test:8} ] , null, null, null]", testTable.toString());
    assertEquals("Cat Value" , testTable.get("Cat"));
    assertEquals(0, testTable.hash("ddd"));
    assertEquals(0, testTable.hash("Cat"));
  }
}
