package linkedList;

import org.junit.jupiter.api.Test;
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
//package linkedList;


//import static org.junit.Assert.*;
import static org.testng.AssertJUnit.assertEquals;

//import org.testng.annotations.Test;
public class AppTest {

  @Test
  public void testLinkList() {

    LinkedList list = new LinkedList();
    list.append(1);
    assertEquals("append new node", "{ 1 } -> ", list.toString());


    LinkedList list3 = new LinkedList();
    list3.append(1);
    list3.append(2);
    list3.append(4);
    list3.insertBefore(4, 3);
    assertEquals("insert before", "{ 1 } -> { 2 } -> { 3 } -> { 4 } -> ", list3.toString());


    LinkedList list4 = new LinkedList();
    list4.append(1);
    list4.append(3);
    list4.append(2);
    list4.append(5);


    list3.insertAfter(2, 100);
    assertEquals("insert before", "{ 1 } -> { 2 } -> { 100 } -> { 3 } -> { 4 } -> ", list3.toString());
  }

}

