/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package graph;

public class App {

  public static void main(String[] args) {

    Graph<String> graph = new Graph<>();
    graph.addNode("10");
    graph.addNode("5");
    graph.addNode("4");
    graph.addNode("1");
    graph.addNode("7");
    graph.addNode("6");
    graph.addEdge("10" , "1");
    graph.addEdge("10" , "7");
    graph.addEdge("5" , "1");
    graph.addEdge("7" , "4");
    System.out.println(graph);
    System.out.println(graph.getNodes());
    System.out.println(graph.getNeighbors("10"));
    System.out.println(graph.getNeighbors("5"));
    System.out.println(graph.getNeighbors("7"));
    System.out.println(graph.size());
  }
}
