/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linkedList;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

    LinkedList showValue = new LinkedList();
    // insert
      showValue.insert(1);
      showValue.insert(2);
      showValue.insert(67);
      showValue.insert(50);
      showValue.insert(4);

    //includes
    System.out.println(showValue.include(3));

    // to string
    System.out.println(showValue.toString());

    }

}

