/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linkedList;

public class App {
  public String getGreeting() {
    return "Hello World!";
  }

  public static void main(String[] args) {
//        System.out.println(new App().getGreeting());
////
//    LinkedList showValue = new LinkedList();
//    // insert
//      showValue.insert(1);
//      showValue.insert(2);
//      showValue.insert(67);
//      showValue.insert(50);
//      showValue.insert(4);
//
//    //includes
//    System.out.println(showValue.include(3));
//
//    // to string
//    System.out.println(showValue.toString());
//
//    }
    //////////////////code 6////////


    LinkedList list = new LinkedList();
    list.append(2);
    list.append(1);
    list.append(4);
    System.out.println("append method" + " " + list.toString());


    list.insertBefore(1, 3);
    System.out.println("insertBefore" + " " + list.toString());


    list.insertAfter(2,100);
    System.out.println("insertAfter" + " " + list.toString());
  }
    }

//
