/*
* This Java source file was generated by the Gradle 'init' task.
  */
  package trees;

import org.junit.jupiter.api.Test;


import static org.junit.jupiter.api.Assertions.*;

class AppTest {
  @Test
  void appHasAGreeting() {
    App classUnderTest = new App();
    assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");


  }


  @Test
  public void testSingleRoot() {
    BinarySearchTree tree = new BinarySearchTree();
    tree.add(10, tree.root);
    assertEquals("BinarySearchTree{root=Node{value=10, left=null, right=null}}", tree.toString());
  }

  @Test public void testAdd() {
    BinarySearchTree tree = new BinarySearchTree();
    tree.add(4, tree.root);
    tree.add(7, tree.root);
    tree.add(3, tree.root);
    tree.add(6, tree.root);

    assertEquals("BinarySearchTree{root=Node{value=4, left=Node{value=3, left=null, right=null}, right=Node{value=7," +
      " left=Node{value=6, left=null, right=null}, right=null}}}", tree.toString());

  }
}
