/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package graph;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {

  @Test
  public void graph() {
    Graph graph = new Graph();
    assertNull(graph.toString());


    graph.addNode("8");
    assertEquals("[8]", graph.getNodes().toString());


    graph.addEdge("8", "8");
    assertEquals("[8]", graph.getNeighbors("8").toString());
    assertEquals("{8=[8]}", graph.nodeList.toString());


    graph.addNode("5");
    graph.addEdge("8", "5");
    assertEquals("[8, 5]", graph.getNeighbors("8").toString());
    assertEquals("[8]", graph.getNeighbors("5").toString());


    assertEquals("[5, 8]", graph.getNodes().toString());

    assertEquals("{5=[8], 8=[8, 5]}", graph.nodeList.toString());

    assertEquals(2, graph.size());

  }

}
