/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hashTable;

public class App {

  public static void main(String[] args) {

    HashTable<java.io.Serializable, Integer> myTable = new HashTable<>();
    myTable.add("mohammad" , 1);
    myTable.add("container" , 2);
    myTable.add("Alaa" , 2);
    myTable.add(555 , 3);
    myTable.add(8 , 4);
    System.out.println(myTable.get("mohammad"));
    System.out.println(myTable.get("container"));
    System.out.println(myTable.get("test"));
    System.out.println(myTable.contains("gogo"));
    System.out.println(myTable.contains("mohammad"));
    System.out.println(myTable.hash("40"));
    System.out.println(myTable.hash("mohammad"));
    System.out.println(myTable.hash("Alaa"));
    System.out.println(myTable);
  }
}
