/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package stackAndQueue;

public class Library {
  public static void main(String[] args) {
    System.out.println("helo");
    Stack<Integer> stackList = new Stack<>();
    stackList.push(1);
    stackList.push(2);
    stackList.push(3);
    stackList.push(4);

    System.out.println(" ============ Stack =========== ");
    System.out.println( stackList);
    System.out.println( stackList.isEmpty());
    System.out.println( stackList.pop());
    System.out.println( stackList.peek());
    System.out.println( stackList);


    Queue<String> queueList = new Queue<>();
    queueList.enqueue("1");
    queueList.enqueue("2");
    queueList.enqueue("3");
    queueList.enqueue("4");

    System.out.println(" ============ Queue =========== ");
    System.out.println( queueList);
    System.out.println(queueList.isEmpty());
    System.out.println(queueList.dequeue());
    System.out.println(queueList.peek());
    System.out.println( queueList);

  }
}

