/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package trees;

import java.util.ArrayList;

import static trees.BinaryTree.breadthFirst;

public class App {

  public static void main(String[] args) {
    BinarySearchTree binarySearchTree = new BinarySearchTree(new Node<>(23));

    Node<Integer> searchNode0 = new Node<>(22);


    Node<Integer> searchNode1 = new Node<>(4);
    Node<Integer> searchNode2 = new Node<>(16, null, searchNode0);
    Node<Integer> searchNode3 = new Node<>(8, searchNode1, searchNode2);
    Node<Integer> searchNode5 = new Node<>(27);

    Node<Integer> searchNode7 = new Node<>(105);
    Node<Integer> searchNode6 = new Node<>(85, null, searchNode7);
    Node<Integer> searchNode4 = new Node<>(42, searchNode5, searchNode6);
    binarySearchTree.root.leftChild = searchNode3;

    binarySearchTree.root.rightChild = searchNode4;

    System.out.println(breadthFirst(binarySearchTree));


//    System.out.println(breadthFirst(newTree));

  }


  public static ArrayList<Integer> breadthFirst(BinaryTree<Integer> newTree) {
    return null;
  }
}
